// const newBaseUrl = 'https://home.tripwerkz.com/new-api/';
const baseUrl = process.env.NEXT_PUBLIC_BASE_URL;
const newBaseUrl = process.env.NEXT_PUBLIC_NEW_BASE_URL;

const MAPBOX_TOKEN = 'pk.eyJ1Ijoic2lyYWotbWljZSIsImEiOiJja21qeGRkeWowdmxlMzJtdWZrN3Ayd3V5In0.6RnI5nnhz0ilBNuM0vtwpA';

const newConstants = {
    // generic response names
    STATUS_CODE: 'statusCode',
    DATA_EXCEPTION: 'dataException',
    ERR_CODE: 'err_code',
    ERR_MSG: 'err_msg',
    DATA: 'data',
    REQUEST_DATA: 'requestData',
    VALUE: 'value',
    ACCEPT_LANGUAGE: "Accept-Language",

    // generic fetach all data
    DISPLAY_LENGTH: 'display-length',
    DISPLAY_START: 'display-start',
    SORT_COLUMN: 'sort-column',
    SORT_DIRECTION: 'sort-direction',
    SEARCH_TEXT: 'search-text',
    PAGE_SIZE: 25,

    // generic names
    TOTAL_ROWS: 'total-rows',
    ROW_NUMBER: 'row-number',
    ROW_NUM: 'row-num',
    ROW_NO: 'row-no',
    LANG_CODE: 'lang-code',
    CLANG_CODE: 'Lang-code',
    CC_LANG_CODE: 'Lang-Code',
    IS_ACTIVE: 'is-active',
    ACTIVE_STATUS: 'active-status',
    LAST_UPDATED_BY: 'last-update-by',

    // ticket amenity types
    TICKET_AMENITY_KEY: 'ticket-amenity-key',
    TICKET_AMENITY_TYPES: 'ticket-amenity-types',
    TICKET_AMENITY_TYPE_KEY: 'ticket-amenity-type-key',
    TICKET_AMENITY_TYPE_DESC: 'ticket-amenity-type-desc',
    TICKET_AMENITY_TYPE_GLYPH_ICON: 'ticket-amenity-type-glyph-icon',
    TICKET_AMENITY_TYPE_LANGUAGES: 'ticket-amenity-type-languages',

    // ticket amenity
    TICKET_AMENITIES: 'ticket-amenities',
    TICKET_AMENITY_NAME: 'ticket-amenity-name',
    TICKET_AMENITY_DEFAULT_PRICE: 'ticket-amenity-default-price',
    TICKET_AMENITY_IS_TAX_AVAILABEL: 'ticket-amenity-is-tax-availabe',
    TICKET_AMENITY_GLYPH_ICON: 'ticket-amenity-glyph-icon',
    TICKET_AMENITY_LANGUAGES: 'ticket-amenity-languages',

    // room category
    ROOM_CATEGORY_NAME: 'room-category-name',
    ROOM_CATEGORIES: 'room-categories',
    ROOM_CATEGORY_KEY: 'room-category-key',
    ROOM_CATEGORY_LANGUAGES: 'room-category-languages',

    //HOTEL_CATEGORY
    HOTEL_CATEGORIES: 'hotel-categories',
    HOTEL_CATEGORY_NAME: 'hotel-category-name',
    HOTEL_CATEGORY_GLYP_CSS: 'hotel-category-glyphcss',
    HOTEL_CATEGORY_KEY: 'hotel-category-key',
    HOTEL_CATEGORY_LANGUAGES: 'hotel-category-languages',
    //HOTEL_TYPE
    HOTEL_TYPE_DESC: 'hotel-type-desc',
    HOTEL_TYPE_KEY: 'hotel-type-key',

    LAST_UPDATE_BY: 'last-update-by',
    LAST_UPDATED_ON: 'last-update-on',

    //
    B2B_PRICE_ADDITION_VALUE: 'b2b-price-addition-value',
    B2B_PRICE_AMENITY_VALUE: 'b2b-price-amenity-value ',
    B2B_PRICE_NET_VALUE: 'b2b-price-net-value ',
    B2B_PRICE_SERVICE_VALUE: 'b2b-price-service-value',
    B2B_PRICE_TAX_VALUE: 'b2b-price-tax-value',
    B2C_PRICE_ADDITION_VALUE: 'b2c-price-addition-value',
    B2C_PRICE_AMENITY_VALUE: 'b2c-price-amenity-value',
    B2C_PRICE_NET_VALUE: 'b2c-price-net-value',
    B2C_PRICE_SERVICE_VALUE: 'b2c-price-service-value',
    B2C_PRICE_TAX_VALUE: 'b2c-price-tax-value',


    // manage rooms
    ROOM_KEY: 'room-key',
    ROOM_NAME: 'room-name',
    ROOM_MIN_PAX: 'room-min-pax',
    ROOM_MAX_PAX: 'room-max-pax',
    ROOM_MIN_ADULTS: 'room-min-adults',
    ROOM_MAX_ADULTS: 'room-max-adults',
    ROOM_MAX_CHILDS: 'room-max-childs',
    ROOM_LANGUAGES: 'room-languages',

    //HOTEL AMMUNITY TYPE
    HOTEL_AMENITY_TYPES: 'hotel-amenity-types',
    HOTEL_AMENITY_TYPE_DESC: 'hotel-amenity-type-desc',
    HOTEL_AMENITY_TYPE_GLYPH_ICON: 'hotel-amenity-type-glyph-icon',
    HOTEL_AMENITY_TYPE_LANGUAGES: 'hotel-amenity-type-languages',
    HOTEL_AMENITY_TYPE_KEY: 'hotel-amenity-type-key',
    // hotel issues
    HOTEL_ISSUES: 'hotel-issues',
    HOTEL_ISSUES_KEY: 'hotel-issues-key',
    HOTEL_ISSUES_TITLE: 'hotel-issues-title',
    HOTEL_ISSUES_DESC: 'hotel-issues-desc',
    HOTEL_ISSUES_LANGUAGES: 'hotel-issues-languages',

    // user login
    USER_NAME: 'UserName',
    PASSWORD: 'Password',
    CPASSWORD: 'ConfirmPassword',

    // user registration
    EMAIL_ID: 'EmailId',
    COMPANY_NAME: 'CompanyName',
    CONTACT_NO: 'ContactNo',
    EMAIL: 'Email',
    // hotel image type
    HOTEL_IMAGE_TYPES: 'hotel-image-types',
    HOTEL_IMAGE_TYPE_KEY: 'hotel-image-type-key',
    HOTEL_IMAGE_TYPE_DESC: 'hotel-image-type-desc',
    HOTEL_IMAGE_TYPE_GLYPH_ICON: 'hotel-image-type-glyph-icon',
    HOTEL_IMAGE_TYPE_LANGUAGES: 'hotel-image-type-languages',
    IMAGE_TYPE_KEY: 'image-type-key',
    IMAGE_PATH_KEY: 'image-path-key',
    IMAGE_PATH: 'image-path',

    // hotel tags
    HOTEL_TAG_KEY: 'hotel-tag-key',
    HOTEL_TAGS: 'hotel-tags',
    HOTEL_TAG_NAME: 'hotel-tag-name',
    HOTEL_TAG_LANGUAGES: 'hotel-tag-languages',

    // room night setup
    ROOM_NIGHT_SETUP_KEY: 'room-night-setup-key',
    ROOM_PLAN_KEY: 'room-plan-key',
    HOTEL_KEY: 'hotel-key',
    ROOM_NIGHT: 'room-night',
    IS_DATERANGE: 'is-daterange',
    EFFECTIVE_FROM: 'effective-from',
    EFFECTIVE_TO: 'effective-to',
    IS_OVERWRITE: 'is-overwrite',
    IS_ALL_DAYS_IN_WEEK: 'is-all-days-in-week',
    IS_SUNDAY: 'is-sunday',
    IS_MONDAY: 'is-monday',
    IS_TUESDAY: 'is-tuesday',
    IS_WEDNESDAY: 'is-wednesday',
    IS_THURSDAY: 'is-thursday',
    IS_FRIDAY: 'is-friday',
    IS_SATURDAY: 'is-saturday',
    DTO_MASTER_ROOM_NIGHT_SETUPS_GRID: 'dtoMasterRoomNightSetUpsGrid',
    // HOTEL AMENITY
    HOTEL_AMENITY_NAME: 'hotel-amenity-name',
    HOTEL_AMENITY_DEFAULT_PRICE: 'hotel-amenity-default-price',
    HOTEL_AMENITY_IS_TAX_AVAILABLE: 'hotel-amenity-is-tax-availabe',
    HOTEL_AMENITIES: 'hotel-amenities',
    HOTEL_AMENITY_LANGUAGES: 'hotel-amenity-languages',
    HOTEL_AMENITY_KEY: 'hotel-amenity-key',
    HOTEL_AMENITY_GLYPH_ICON: 'hotel-amenity-glyph-icon',
    HOTEL_IMAGES: 'hotel-images',

    // ROOM PRICE COMMENTS
    ROOM_PRICE_COMMENTS: 'room-price-comments',
    ROOM_PRICE_COMMENTS_DESC: 'room-price-comments-desc',
    ROOM_PRICE_COMMENTS_KEY: 'room-price-comments-key',
    ROOM_PRICE_COMMENTS_TITLE: 'room-price-comments-title',
    ROOM_PRICE_COMMENTS_LANGUAGES: 'room-price-comments-languages',
    COUNTRY_KEY: 'country-key',

    //AUTH
    ENCRYPT_EMAIL: 'EncryptEmail',
    //country state provinces
    COUNTRY_NAME: 'country-name',
    CITY_KEY: 'city-key',
    CITY_NAME: 'city-name',
    PROVINCE_KEY: 'province-key',
    PROVINCE_NAME: 'province-name',
    LABEL: 'label',

    // agent profile
    CLIENT_LICENSE_NO: 'ClientLicenseNo',
    CLIENT_REG_NO: 'ClientRegisterationNo',
    CLIENT_CODE: 'ClientCode',
    CLIENT_NAME: 'ClientName',
    CLIENT_EMAIL: 'ClientEmail',
    CLIENT_USERNAME: 'UserName',
    CLIENT_WEB_SITE: 'ClientWebsite',
    CLIENT_REMARKS: 'ClientRemarks',
    CLIENT_BRANCH_REG_NO: 'ClientBranchRegNo',
    CLIENT_BRANCH_NAME: 'ClientBranchName',
    CLIENT_BRANCH_ADDRESS: 'ClientBranchAddress',
    CLIENT_BRANCH_CITY: 'ClientBranchCity',
    CLIENT_BRANCH_STATE: 'ClientBranchState',
    CLIENT_BRANCH_COUNTRY: 'ClientBranchCountry',
    CLIENT_BRANCH_POST_CODE: 'ClientBranchPostCode',
    CLIENT_BRANCH_REMARK: 'ClientBranchRemark',
    CLIENT_BILLING_CURRENCY: 'ClientBillingCurrency',
    CLIENT_BRANCH_TELE_NO1: 'ClientBranchTeleNo1',
    CLIENT_BRANCH_TELE_NO2: 'ClientBranchTeleNo2',
    CLIENT_BRANCH_MOBILE_NO1: 'ClientBranchMobileNo1',
    CLIENT_BRANCH_MOBILE_NO2: 'ClientBranchMobileNo2',
    CLIENT_BRANCH_EMAIL: 'ClientBranchEmail',
    IS_HEAD_OFFICE: 'IsHeadOffice',
    CLIENT_BRANCH_INFOS: 'clientBranchInfos',

    //  TICKET SUPPLIERS
    TICKET_MODULE_KEY: 'ticket-module-key',
    TICKET_SUPPLIER_REGNO: 'ticket-supplier-regno',
    TICKET_SUPPLIER_NAME: 'ticket-supplier-name',
    TICKET_SUPPLIER_ADDRESS: 'ticket-supplier-address',
    TICKET_SUPPLIER_CITY_KEY: 'ticket-supplier-city-key',
    TICKET_SUPPLIER_CITY_NAME: 'ticket-supplier-city-name',
    TICKET_SUPPLIER_STATE_KEY: 'ticket-supplier-state-key',
    TICKET_SUPPLIER_COUNTRY_NAME: 'ticket-supplier-country-name',
    TICKET_SUPPLIER_COUNTRY_KEY: 'ticket-supplier-country-key',
    TICKET_SUPPLIER_PINCODE: 'ticket-supplier-pincode',
    TICKET_SUPPLIER_REMARK: 'ticket-supplier-remark',
    TICKET_SUPPLIER_TELENO1: 'ticket-supplier-teleno1',
    TICKET_SUPPLIER_TELENO2: 'ticket-supplier-teleno2',
    TICKET_SUPPLIER_MOBILENO1: 'ticket-supplier-mobileno1',
    TICKET_SUPPLIER_MOBILENO2: 'ticket-supplier-mobileno2',
    TICKET_SUPPLIER_FAX1: 'ticket-supplier-fax1',
    TICKET_SUPPLIER_FAX2: 'ticket-supplier-fax2',
    TICKET_SUPPLIER_WEBURL: 'ticket-supplier-weburl',
    TICKET_SUPPLIER_EMAIL: 'ticket-supplier-email',
    TICKET_SUPPLIER_LANGUAGES: 'ticket-supplier-languages',
    TICKET_SUPPLIER_LINKS: 'ticket-supplier-links',
    TICKET_TYPE_KEY: 'ticket-type-key',
    TICKET_SUPPLIER_KEY: 'ticket-supplier-key',
    // ticket stock
    TICKET_STOCK_KEY: 'ticket-stock-key',
    TICKET_STOCKS: 'ticket-stocks',
    TICKET_PLAN_KEY: 'ticket-plan-key',
    TICKET_COST_PRICEB2C: 'ticket-cost-priceb2c',
    TICKET_COST_PRICEB2B: 'ticket-cost-priceb2b',
    TICKET_MRP_PRICE: 'ticket-mrp-price',
    TICKET_STOCK: 'ticket-stock',
    TICKET_PREFIX: 'ticket-prefix',
    TICKET_CODE_LENGTH: 'ticket-code-length',
    TICKET_SUFFIX: 'ticket-suffix',
    TICKET_START_NUMBER: 'ticket-start-number',
    TICKET_END_NUMBER: 'ticket-end-number',
    IS_OPENING_STOCK: 'is-opening-stock',
    IS_OPENING_STOCK_STATUS: 'is-opening-stock-status',
    DATE_OF_PURCHASE: 'date-of-purchase',
    PURCHASE_REF_NUMBER: 'purchase-ref-number',
    IS_SOLD_OUT: 'is-sold-out',
    IS_SOLD_OUT_STATUS: 'is-sold-out-status',
    TICKET_STOCK_SERIALS: 'ticket-stock-serials',
    BARCODE_NUMBER: 'barcode-number',
    BARCODE_DATA: 'barcode-data',

    //  HOTEL
    HOTEL_NAME: 'hotel-name',
    HOTEL_ADDRESS: 'hotel-address',
    HOTEL_CITY_NAME: 'hotel-city-name',
    HOTEL_PROVINCE_NAME: 'hotel-province-name',
    HOTEL_COUNTRY_NAME: 'hotel-country-name',
    HOTEL_EMAIL1: 'hotel-email1',
    HOTEL_OFFICE_PHONE1: 'hotel-office-phone1',
    HOTEL_OFFICE_PHONE2: 'hotel-office-phone2',
    HOTEL_CONTACT_PERSON: 'hotel-contact-person',
    HOTEL_PHONE1: 'hotel-phone1',
    HOTEL_REGNO: 'hotel-regno',
    HOTELS: 'hotels',
    HOTEL_WEB_SITE: 'hotel-website',
    HOTEL_CITY_KEY: 'hotel-city-key',
    HOTEL_PROVINCE_KEY: 'hotel-province-key',
    HOTEL_COUNTRY_KEY: 'hotel-country-key',
    HOTEL_POSTAL_CODE: 'hotel-postal-code',
    HOTEL_LATITUDE: 'hotel-latitude',
    HOTEL_LONGITUDE: 'hotel-longitude',
    HOTEL_FEATURED_IMAGE_PATH_KEY: 'hotel-featured-image-path-key',

    // FORM IMAGE UPLOAD
    DOC_TYPE_KEY: 'doc-type-key',
    FORM_NAME: 'form-name',
    UPLOAD_FILE: 'uploaded-file',
    FILE_PATH: 'file_path',
    FILE_KEY: 'fileKey',
    FILE_NAME: 'fileName',
    FILE_INFOS: 'fileInfos',
    DOC_TYPE_NAME: 'documentTypeName',
    DOCUMENT_TYPE_FLAG: 'DocumentTypeFlag',
    DOCUMENT_TYPE_NAME: 'document-type-name',
    IS_MANDATORY: 'is-mandatory',
    DOCUMENT_TYPE_KEY: 'document-type-key',
    C_FILE_KEY: 'File-Key',
    CLIENT_BRANCH_ID: 'clientBranchId',
    CLIENT_ID: 'clientId',

    // TICKET_IMAGE
    TICKET_IMAGES_TYPES: 'ticket-image-types',
    TICKET_IMAGE_TYPE_DESC: 'ticket-image-type-desc',
    TICKET_IMAGE_TYPE_KEY: 'ticket-image-type-key',
    TICKET_IMAGE_TYPE_LANGUAGES: 'ticket-image-type-languages',

    // TICKET_TAGS
    TICKET_TAGS: 'ticket-tags',
    TICKET_TAG_KEY: 'ticket-tag-key',
    TICKET_TAG_NAME: 'ticket-tag-name',
    TICKET_TAG_LANGUAGES: 'ticket-tag-languages',

    // manage ticket
    TICKETS: 'tickets',
    SUPPLIER_KEY: 'supplier-key',
    TICKET_KEY: 'ticket-key',
    TICKET_NAME: 'ticket-name',
    TICKET_CODE: 'ticket-code',
    TICKET_LANGUAGES: 'ticket-languages',
    TICKET_AMENITY_LINKS: 'ticket-amenity-links',
    TICKET_IMAGE_LINKS: 'ticket-image-links',
    TICKET_IMAGE_PATH: 'ticket-image-path',

    // ticket type
    TICKET_SUPPLIERS: 'ticket-suppliers',
    TICKET_TYPES: 'ticket-types',
    TICKET_TYPE_NAME: 'ticket-type-name',
    IS_ZERO_COST: 'is-zero-cost',

    HOTEL_TYPES: 'hotel-types',
    TICKET_MODULES: 'ticket-modules',
    TICKET_MODULE_DESC: 'ticket-module-desc',
    // mapbox token
    // TO DO, move it to ENV File
    MAPBOX_TOKEN: 'pk.eyJ1Ijoic2lyYWotbWljZSIsImEiOiJja21qeGRkeWowdmxlMzJtdWZrN3Ayd3V5In0.6RnI5nnhz0ilBNuM0vtwpA',

    // near place
    HOTEL_NEAR_BY_PLACES: 'hotel-categories',
    HOTEL_NEAR_BY_PLACE_KEY: 'hotel-near-by-place-key',
    HOTEL_NEAR_BY_PLACE_DESC: 'hotel-near-by-place-desc',
    HOTEL_NEAR_PLACE_TYPE_KEY: 'hotel-near-place-type-key',
    HOTEL_GLYPH_ICON_NEAR_PLACE: 'hotel-glyp-icon-near-place',
    HOTEL_NEAR_BY_PLACE_LATITUDE: 'hotel-near-by-place-latitude',
    HOTEL_NEAR_BY_PLACE_LONGITUDE: 'hotel-near-by-place-longitude',
    HOTEL_NEAR_BY_PLACE_LANGUAGES: 'hotel-near-by-place-languages',

    // near place type
    HOTEL_NEAR_PLACE_TYPES: 'hotel-categories',
    HOTEL_NEAR_BY_PLACE_TYPE_DESC: 'hotel-near-by-place-type-desc',
    HOTEL_GLYPH_ICON_NEAR_PLACE_TYPE: 'hotel-glyp-icon-near-place-type',
    NEAR_PLACE_KEY: 'near-place-key',
    NEAR_PLACE_DESC: 'near-place-desc',
    // Ticket plans
    TICKET_PLANS: 'ticket-plans',
    TICKET_PLAN_NAME: 'ticket-plan-name',
    LANGUAGE_CODE: 'language-code',
    LANGUAGE_DESC: 'language-desc',

    // room plan
    ROOM_PLAN_NAME: 'room-plan-name',
    IS_OVERWRITE_PRICE: 'is-overwrite-price',
    IS_ALLDAYS_IN_WEEK: 'is-alldays-in-week',
    IS_ALL_DAYS_IS_WEEK_STR: 'is-all-days-in-week-str',
    ROOM_PLAN_LANGUAGES: 'room-plan-languages',
    ROOM_PLAN_AMENITY_LINKS: 'room-plan-amenties-links',
    IS_CHARGEABLE: 'is-chargeable',
    IS_SHOW: 'is-show',
    ROOM_AMENITY_PRICE: 'room-amenity-price',
    ROOM_AMENITY_KEY: 'room-amenity-key',
    ROOM_PLAN_CANCEL_POLICY_RULES: 'room-plan-cancel-policy-rules',
    ROOM_CANCEL_RULE_NAME: 'room-cancel-rule-name',
    ROOM_PLAN_CANCEL_POLICIES: 'room-plan-cancel-policies',
    REFUND_TYPE_KEY: 'refund-type-key',
    DAYS_BEFORE_CHECK_IN: 'days-before-check-in',
    CANCELATION_VALUE: 'cancelation-value',
    ROOM_PLANS: 'room-plans',
    IS_SHOW_PRICE_WITH_TAX_BREAKUP: 'is-show-price-with-tax-break',
    CLIENT_MARGIN_VALUE: 'client-margin-value',
    CLIENT_MARGIN_TYPE: 'client-margin-type',
    // room plan refund
    IS_DATE_RANGE: 'is-date-range',
    REFUND_TYPES: 'refund-types',
    REFUND_TYPE_DESC: 'refund-type-desc',

    // TIcket_plan
    ACTIVE_HOURS_FROM: 'active-hours-from',
    ACTIVE_HOURS_TO: 'active-hours-to',
    EXPIRE_DATE: 'expire-date',
    IS_CHILD_ALLOWED: 'is-child-allowed',
    IS_ADULT_ALLOWED: 'is-adult-allowed',
    IS_SENIOR_ALLOWED: 'is-senior-allowed',
    IS_PAX_WISE_PRICE: 'is-pax-wise-price',
    PAX_MIN_CHILD: 'pax-min-child',
    PAX_MAX_CHILD: 'pax-max-child',
    PAX_MIN_ADULT: 'pax-min-adult',
    PAX_MAX_ADULT: 'pax-max-adult',
    PAX_MIN_SENIOR: 'pax-min-senior',
    PAX_MAX_SENIOR: 'pax-max-senior',
    IS_SERVICE_ITEM: 'is-service-item',
    IS_EXPIRE: 'is-expire',
    TICKET_PLAN_CANCEL_POLICIES: 'ticket-plan-cancel-policies',
    TICKET_PLAN_CANCEL_POLICY_RULES: 'ticket-plan-cancel-policy-rules',
    TICKET_PLAN_AMENITY_LINKS: 'ticket-plan-amenties-links',
    TICKET_CANCEL_RULE_NAME: 'ticket-cancel-rule-name',
    TICKET_AMENITY_PRICE: 'ticket-amenity-price',
    HOTEL_NEAR_PLACES: 'hotel-near-places',
    C_HOTEL_NAME: 'HotelName',
    C_HOTEL_ADDRESS: 'HotelAddress',
    HOTEL_DESCRIPTION_LABEL: 'hotel-description-label',
    HOTEL_DESCRIPTION_TEXT: 'hotel-description-text',
    HOTEL_DESCRIPTIONS: 'hotel-descriptions',

    // hotel room links
    HOTEL_ROOM_LINKS: 'hotel-tags',
    ROOM_ALLOTMENT: 'room-allotment',
    CHILD_AGE_LIMIT: 'child-age-limit',
    HOTEL_ROOM_AMENITY_LINKS: 'hotel-room-amenity-links',
    HOTEL_ROOM_IMAGE_PATH_LINKS: 'hotel-room-image-path-links',
    HOTEL_IMAGE_PATH_KEY: 'hotel-image-path-key',
    HOTEL_LANGUAGES: 'hotel-languages',
    URL: 'url',

    // Room plan price
    ROOM_SEASIONALTIES_LISTS: 'room-seasionalties-lists',
    ROOM_SEASIONALITY_NAME: 'hotel-seasonality-name',
    IS_APPROVED_STATUS: 'is-approved-status',
    ROOM_RATE_B2C: 'room-rate-b2c',
    ROOM_RATE_B2B: 'room-rate-b2b',
    IS_FLAT_TAX_RATE: 'is-flat-tax-rate',
    TAX_VALUE: 'tax-value',
    IS_FLAT_SERVICE_RATE: 'is-flat-service-rate',
    SERVICE_VALUE: 'service-value',
    IS_FLAT_ADDITIONAL_RATE: 'is-flat-additonal-rate',
    ADDITIONAL_VALUE: 'additional-value',
    IS_INCLUSIVE_RATE: 'is-inclusive-rate',
    HOTEL_IMAGE_PATH_KEY: 'hotel-image-path-key',
    HOTEL_LANGUAGES: 'hotel-languages',
    URL: 'url',

    TICKET_PLAN_LABEL: 'ticket-plan-label',
    TICKET_PLAN_TEXT: 'ticket-plan-text',
    IS_PRINT_VOUCHER: 'is-print-voucher',
    TICKET_PLAN_DESCRIPTION: 'ticket-plan-descriptions',
    TICKET_PLAN_PAXES: 'ticket-plan-paxes',
    TICKET_PLAN_LANGUAGES: 'ticket-plan-languages',

    SEARCH_KEYWORD: 'searchKeyword',

    HOTEL_SEASONALITY_NAME: 'hotel-seasonality-name',
    IS_APPROVED: 'is-approved',
    IS_INCLUSIVE_PRICE: 'is-inclusive-price',
    ROOM_PLAN_PRICE_RESPONSE_DETAILS: 'room-plan-price-response-details',
    ROOM_PLAN_PRICE_RESPONSE_DETAILS_EDIT: 'room-plan-price-response-details-edit',
    MARKUP_TYPE: 'markup-type',
    MARKUP_PERCENTAGE: 'markup-percentage',
    DATE: 'date',
    B2B_COST_RATE: 'b2b-cost-rate',
    B2B_SALE_RATE: 'b2b-sale-rate',
    B2B_COST_TAX_PERCENTAGE: 'b2b-cost-tax-percentage',
    B2B_COST_TAX_RATE: 'b2b-cost-tax-rate',
    B2B_SALE_TAX_PERCENTAGE: 'b2b-sale-tax-percentage',
    B2B_SALE_TAX_RATE: 'b2b-sale-tax-rate',
    B2B_COST_SERVICE_PERCENTAGE: 'b2b-cost-service-percentage',
    B2B_COST_SERVICE_RATE: 'b2b-cost-service-rate',
    B2B_SALE_SERVICE_PERCENTAGE: 'b2b-sale-service-percentage',
    B2B_SALE_SERVICE_RATE: 'b2b-sale-service-rate',
    B2B_COST_ADDTIONAL_PERCENTAGE: 'b2b-cost-addtional-percentage',
    B2B_COST_ADDTIONAL_RATE: 'b2b-cost-addtional-rate',
    B2B_SALE_ADDTIONAL_PERCENTAGE: 'b2b-sale-addtional-percentage',
    B2B_SALE_ADDTIONAL_RATE: 'b2b-sale-addtional-rate',
    NET_B2B_COST: 'net-b2b-cost',
    NET_B2B_SALE: 'net-b2b-sale',
    B2C_COST_RATE: 'b2c-cost-rate',
    B2C_SALE_RATE: 'b2c-sale-rate',
    B2C_COST_TAX_PERCENTAGE: 'b2c-cost-tax-percentage',
    B2C_COST_TAX_RATE: 'b2c-cost-tax-rate',
    B2C_SALE_TAX_PERCENTAGE: 'b2c-sale-tax-percentage',
    B2C_SALE_TAX_RATE: 'b2c-sale-tax-rate',
    B2C_COST_SERVICE_PERCENTAGE: 'b2c-cost-service-percentage',
    B2C_COST_SERVICE_RATE: 'b2c-cost-service-rate',
    B2C_SALE_SERVICE_PERCENTAGE: 'b2c-sale-service-percentage',
    B2C_SALE_SERVICE_RATE: 'b2c-sale-service-rate',
    B2C_SALE_ADDTIONAL_PERCENTAGE: 'b2c-sale-addtional-percentage',
    B2C_SALE_ADDTIONAL_RATE: 'b2c-sale-addtional-rate',
    B2C_COST_ADDTIONAL_PERCENTAGE: 'b2c-cost-addtional-percentage',
    B2C_COST_ADDTIONAL_RATE: 'b2c-cost-addtional-rate',
    AMENITY_RATE: 'amenity-rate',
    NET_B2C_COST: 'net-b2c-cost',
    NET_B2C_SALE: 'net-b2c-sale',
    SOLD_OUT_FLAG: 'sold-out-flag',
    ROOM_PLAN_REQUEST_DETAILS: 'room-plan-request-details',

    // ticket price comments
    TICKET_PRICE_COMMENTS_KEY: 'ticket-price-comments-key',
    TICKET_PRICE_COMMENTS_TITLE: 'ticket-price-comments-title',
    TICKET_PRICE_COMMENTS_DESC: 'ticket-price-comments-desc',
    TICKET_PRICE_COMMENTS: 'ticket-price-comments',
    TICKET_PRICE_COMMENTS_LANGUAGES: 'ticket-price-comments-languages',

    // ticket price plan
    TICKET_RATE_B2C: 'ticket-rate-b2c',
    TICKET_RATE_B2B: 'ticket-rate-b2b',
    TICKET_SEASONALITY_NAME: 'ticket-seasonality-name',
    TICKET_SEASONALITY_KEY: 'ticket-seasonality-key',
    TICKET_SEASONALITIES_LISTS: 'ticket-seasionalties-lists',
    TICKET_PLAN_PRICE_RESPONSE_DETAILS: 'ticket-plan-price-response-details',
    TICKET_PLAN_PRICE_RESPONSE_DETAILS_EDIT: 'ticket-plan-price-response-details-edit',
    TICKET_PRICE_SERVICE_TYPE: 'ticket-price-serivce-type',
    TICKET_PRICE_ADDITION_TYPE: 'Ticket-Price-Addition-Type',
    TICKET_ALLOTMENT: 'ticket-allotment',

    ROOM_PRICE_SERVICE_TYPE: 'room-price-serivce-type',
    ROOM_PRICE_ADDITION_TYPE: 'Room-Price-Addition-Type',
    SEASONALITY_KEY: 'seasonality-key',

    // Ledger Master
    LEDGER_NAME: 'ledger-name',
    LEDGER_GROUP_KEY: 'ledger-group-key',
    LEDGER_BALANCE: "ledger-balance",
    LEDGER_OPENING_BALANCE: 'ledger-opening-balance',
    LEDGER_CURRENCY_CODE: 'ledger-currency-code',
    LEDGER_OPENING_DATE: 'ledger-opening-date',
    LEDGER_LANGUAGES: 'ledger-languages',
    LEDGER_KEY: 'ledger-key',

    // Ledger Group
    LEDGER_GROUP_NAME: 'ledger-group-name',
    LEDGER_GROUP_PARENT_KEY: 'ledger-group-parent-key',
    LEDGER_GROUP_LANGUAGES: 'ledger-group-languages',
    LEDGER_GROUPS: 'ledger-accounts',


    // MOP_MASTERS
    MOP_MASTERS: "mop-masters",
    MOP_NAME: "mop-name",
    IS_LEDGER_CONFIG_REQ: "is-ledger-config-req",
    IS_SYSTEM_DEFAULT_STATUS: "is-system-default-status",
    MOP_REMARK_FIELD1_TYPE: "mop-remarks-field1-type",
    MOP_REMARK_FIELD1_CAPTION: "mop-remarks-field1-caption",
    MOP_REMARK_FIELD2_TYPE: "mop-remarks-field2-type",
    MOP_REMARK_FIELD2_CAPTION: "mop-remarks-field2-caption",
    LEDGER_ACCOUNTS: "ledger-accounts",
    REMARK_FIELD_TYPE_VALUE: "remark-field-tpye-value",
    REMARK_FIELD_TYPE: "remark-field-tpye",
    MODEOF_PAYMASTER_LANGUAGES: "modeof-paymaster-languages",
    MOP_DETAIL: "mop-details",
    MOP_MASTER_KEY: "mop-master-key",
    HOTEL_SEASONALITY_KEY: "hotel-seasonality-key",

    // Bank Master
    BANK_KEY: "bank-key",
    BANK_NAME: "bank-name",
    BANK_ACCOUNT_NO: "bank-account-no",
    BANK_ADDRESS: "bank-address",
    BANK_CITY_KEY: "bank-city-key",
    BANK_PROVINCE_KEY: "bank-province-key",
    BANK_COUNTRY_KEY: "bank-country-key",
    BANK_POSTCODE: "bank-postcode",
    BANK_TEL: "bank-tel",
    BANK_FAX: "bank-fax",
    BANK_EMAIL: "bank-email",
    BANK_BRANCH_NAME: "bank-branch-name",
    BANK_LANGUAGES: "bank-languages",
    ADMIN_BANKS: "admin-banks",
    BANK_CITY_NAME: "bank-city-name",
    BANK_STATE_NAME: "bank-state-name",
    BANK_COUNTRY_NAME: "bank-country-name",

    // ledger group dropdown new
    LEDGER_GROUP_CHILD_KEY: "ledger-group-child-key",
    LEDGER_GROUP_PARENT_NAME: "ledger-group-parent-name",
    LEDGER_GROUP_CHILD: "ledger-group-child",

    // ledger journal
    TXN_MASTER_KEY: "txn-master-key",
    TXN_DATE: "txn-date",
    TXN_TYPE: "txn-type",
    TXN_REC_NUMBER: "txn-rec-number",
    TXN_REC_AMOUNT: "txn-rec-amount",
    TXN_REMARK: "txn-remark",
    TXN_REMARKS: "txn-remarks",
    LEDGER_TRANS_DETAILS: "ledger-trans-details",
    ACCOUNT_KEY: "account-key",
    ACCOUNT_NAME: "account-name",
    TXN_AMOUNT: "txn-amount",
    LEDGER_JOURNALS: "ledger-journals",
    FINANCE_YEAR_KEY: "finance-year-key",
    TXN_STATUS: "txn-status",
    MOP_REMARKS_FIELD1_VALUE: "mop-remarks-field1-value",
    MOP_REMARKS_FIELD2_VALUE: "mop-remarks-field2-value",

    // trans type
    TRANS_TYPE_NAME: "trans-type-name",
    TRANS_TYPE_VALUE: "trans-type-value",

    // Update Currency Margin
    CURRENCY_NAME: "currency-name",
    CURRENCY_CODE: "currency-code",
    EXCHANGE_RATE: "exchage-rate",
    BASE_CURRENCY: "base-currency",
    MARGIN_TYPE_NAME: "margin-type-name",
    MARGIN_TYPE_VALUE: "margin-type-value",
    MARGIN_RATE: "margin-rate",
    BOARD_RATE: "board-rate",
    BUY_MARGIN_TYPE_NAME: "buy-margin-type-name",
    BUY_MARGIN_TYPE_VALUE: "buy-margin-type-value",
    BUY_MARGIN_RATE: "buy-margin-rate",
    BUY_BOARD_RATE: "buy-board-rate",
    CURRENCY_RATE: "currency-rate",
    LAST_UPDATE_DATE: "last-update-date",
    MARGIN_TYPES: "margin-types",

    // purchase invoice 
    PURCHASE_INVOICES: "purchase-invoices",
    INVOICE_NUMBER: "invoice-number",
    INVOICE_COST: "invoice-cost",
    INVOICE_AMOUNT: "invoice-amount",
    INVOICE_TYPE: "invoice-type",
    SUPPLIER_NAME: "supplier-name",
    INVOICE_REMARKS: "invoice-remarks",
    INVOICE_STATUS: "invoice-status",
    INVOICE_REF_NUMBER: "invoice-ref-number",
    INVOICE_DATE: "invoice-date",
    EXPIRY_DAYS: "expiry-days",
    PURCHASE_INVOICE_DETAILS: "pruchase-invoice-details",
    TICKET_QUANTITY: "ticket-quantity",
    TICKET_COST: "ticket-cost",
    TICKET_MRP: "ticket-mrp",
    PURCHASE_INVOICE_DATA: "pruchase-invoice-excel-data",
    PURCHASE_INVOICE_EXCEL_DATA: "pruchase-invoice-excel-data",
    SNO: "Sno",
    SERIAL_NUMBER: "serial-number",
    QR_OR_BARCODE_DATA: "qr-or-barcode-data",
    COMMENTS: "comments",
    SUPPLIER_MODULE_KEY: "supplier-module-key",
    SUPPLIER_MODULE_CODE: "supplier-module-code",
    SUPPLIER_TICKETS: "supplier-tickets",
    SUPPLIER_TICKET_TYPES: "supplier-ticket-types",

    // Dashboard
    SEARCH_VALUE: "search-value",
    SALES_DATA: "sales-data",
    CATEGORY_TYPE: "category-type",
    SALES_VALUE: "sales-value",
    DATE_VALUE: "date-value",
    X_AXIS_DATA: "x-axis-data",
    Y_AXIS_DATA: "y-axis-data",
    DISPLAY_NAME: "display-name",
    AXIS_VALUE: "axis-value",
    INVOICE_PERSON: "invoice-person",
    INVOICE_VALUE: "invoice-value",
    INVOICE_DATE: "invoice-date",
    PAYMENT_AMOUNT: "payment-amount",
    PAYMENT_CURRENCY: "payment-currency",
    PAYMENT_VENDOR: "payment-vendor",

    AXIS_VALUE: "axis-value",
    STOCK_KEY: "stock-key",

    // Ticket code 
    TICKET_STOCKS: "ticket-stocks",
    TICKET_SUPPLIER_NAME: "ticket-supplier-name",
    TICKET_OPEN_STOCK_DETAILS: "ticket-open-stock-details",
    OPEN_STOCK_EXCEL_DATA: "open-stock-excel-data",

    SERIAL_NO: "serial-no",
    B2B_RATE: "b2b-rate",
    RATE: "rate",
    GRAND_TOTAL: "grand-total",
    TAX_RATE: "tax-rate",
    SERVICE_RATE: "service-rate",
    ADDITIONAL_RATE: "additional-rate",
    NET_RATE: "net-rate",
    B2C_RATE: "b2c-rate",
    TAX_PERCENTAGE: "tax-percentage",
    SERVICE_PERCENTAGE: "service-percentage",
    ADDITIONAL_COST_PERCENTAGE: "addtional-cost-percentage",
    PLAN_PRICE_DETAILS: "plan-price-details",
    PAX_WISE_PRICE_DETAILS: "pax-wise-price-details",

    PRICE_COMMENTS_KEY: "price-comments-key",
    B2B_PRICE: "b2b-price",
    NET_VALUE: "net-value",
    B2C_PRICE: "b2c-price",
    TAX_TYPE: "tax-type",
    SERVICE_TYPE: "service-type",
    ADDITIONAL_TYPE: "addition-type",
    IS_PAX_WISE: "is-paxwise",

    AMENITY_VALUE: "amenity-value",
    ROOM_PLAN_PAX_PRICE: "room-plan-pax-price",
    PAX_ADULT: "pax-adult",
    PAX_CHILD: "pax-child",
    ROOM_PLAN_PRICE_DETAILS: "room-plan-price-details",

    ROOM_PLAN_DATE: "room-plan-date",
    HOTEL_TAX_VALUE: "hotel-tax-value",
    HOTEL_SERVICE_VALUE: "hotel-service-value",
    HOTEL_ADDITIONAL_VALUE: "hotel-addtional-value",
    HOTEL_TAX_RULE_KEY: "hotel-tax-rule-key",
    LATTITUDE: "latitude",
    LONGITUDE: "longitude",
    DISTANCE_KM: "distance-km",
    TAX_RULE_KEY: "tax-rule-key",
    TAX_RULE_NAME: "tax-rulename",

    //event Ticket Category
    TICKET_CATEGORY_NAME: "ticket-category-name",
    TICKET_CATEGORY_LANGUAGES: "ticket-category-languages",
    TICKET_CATEGORY_KEY: "ticket-category-key",
    TICKET_CATEGORYS: "ticket-categorys",

    AMENITY_CHARGE: "amenity-charge",
    HOTEL_ROOM_AMENITY_NAME: "hotel-room-amenity-name",

  B2C_NET_VALUE:"b2c-net-value",
  B2B_NET_VALUE:"b2c-net-value",
  ROOM_PLAN_PRICE_KEY:"room-plan-price-key",

    ADDITION_VALUE: "addition-value",
    BEGIN_DATE: "begin-date",
    TICKET_FEATURED_IMAGE_KEY: "ticket-featured-image",
    IS_STOCK_TICKET: "is-stock-ticket",
    TICKET_TAG_LINKS: "ticket-tag-links",
    TICKET_AMENITY_KEY: "ticket-amenity-key",
    TICKET_IMAGE_TYPE_GLYPH_ICON: "ticket-image-type-glyphicon",
    TICKET_DESCRIPTION_TEXT: "ticket-description-text",
    TICKET_DESCRIPTION_LABEL: "ticket-description-label",
    TICKET_DESCRIPTION: "ticket-description",
    TICKET_DESCRIPTIONS: "ticket-descriptions",
    TICKET_IMAGE_KEY: "ticket-image-key",
    SUPPLIER_ADDITIONAL_PERCENTAGE: "supplier-addtional-precentage",
    SUPPLIER_SERVICE_PERCENTAGE: "supplier-service-precentage",
    SUPPLIER_TAX_PERCENTAGE: "supplier-tax-precentage",
    SUPPLIER_TAX_RULE_KEY: "supplier-tax-rule-key",
    LEDGER_CURR_CODE: "ledger-curr-code",
    GROUP_ALLOTMENT: "group-allotment",
    IS_GROUP_TICKET: "is-group-ticket",
    IS_TERM_DATE: "is-term-date",
    MAX_ALLOWED: "max-allowed",
    TICKET_TERM_DATE: "ticket-term-date",
    IS_SHOW_ON_LISTING: "is-show-on-listing",
    TICKET_RATE_REGULAR_B2B: "ticket-rate-regular-b2b",
    TICKET_RATE_REGULAR_B2C: "ticket-rate-regular-b2c",
    IS_TAX_INCLUSION: "is-tax-inclusion",
    RATE_COMMENTS_KEY: "rate-comment-key",
    TICKET_PLAN_RATES: "ticket-plan-rates",
    TICKET_SEASONALITY_LISTS: "ticket-seasonality-lists",

    B2B_TAX_VALUE: "b2b-tax-value",
    B2B_SERVICE_VALUE: "b2b-service-value",
    B2B_ADDITIONAL_VALUE: "b2b-additional-value",
    B2B_AMENITY_VALUE: "b2b-amenity-value",
    B2B_NET_VALUE: "b2b-net-value",
    B2C_SERVICE_VALUE: "b2c-service-value",
    B2C_ADDITIONAL_VALUE: "b2c-additional-value",
    B2C_AMENITY_VALUE: "b2c-amenity-value",
    B2C_TAX_VALUE: "b2c-tax-value",

    B2B_ADDITION_VALUE: "b2b-addition-value",
    B2C_ADDITION_VALUE: "b2c-addition-value",
    LEDGER_GROUP_TYPE:"ledger-group-type",

    CLIENT_BRANCH_KEY: "client-branch-key",
    HOTEL_NEAR_PLACE_TYPE:"hotel-near-place-types",

    // BASECURRENCY:"baseCurrency"
    BASECURRENCY:"ClientCurrency",
    CLIENT_LANGUAGE:"ClientLanguage",
    TICKET_TYPE_LINKS: "ticket-type-links",

    IS_AGE_LIMIT: 'is-age-limit',
    AGE_FROM: 'age-from',
    AGE_TO: 'age-to',

};

export { MAPBOX_TOKEN, newBaseUrl, newConstants };
