const reportConstants = {
  // generic fetach all data
  DISPLAY_LENGTH: 'display-length',
  DISPLAY_START: 'display-start',
  SORT_COLUMN: 'sort-column',
  SORT_DIRECTION: 'sort-direction',
  SEARCH_TEXT: 'search-text',
  START_DATE: 'start-date',
  END_DATE: 'end-date',
  IS_ACTIVE: 'is-active',
  LEDGER_KEY: 'ledger-key',
  STATUS: 'Status',
  CLIENT_BRANCH_KEY: 'client-branch-key',
  CLIENT_BRANCH_NAME: 'client-branch-name',
  CLIENT_BRANCHES: 'client-branches',

  LEDGER_TRANS: 'ledger-trans',
  LEDGER_CUM_SUM: 'ledger-cum-sum',
  LEDGER_JOURNAL: 'ledger-journal',
  LEDGER_ACCOUNTS: 'ledger-accounts',
  LEDGER_EXPENSE: 'ledger-expense',
  SALES_DTLS: 'sales-dtls',
  LEDGER_NAME: 'ledger-name',
  OPEN_BAL: 'open-bal',

  OPENING_BAL: 'opening-bal',
  CLOSING_BAL: 'closing-bal',

  MOP_NAME: 'mop-name',
  MOP_REMARKS_1_CAP: 'mop-remarks-field1-caption',
  MOP_REMARKS_1_VALUE: 'mop-remarks-field1-value',
  MOP_REMARKS_2_CAP: 'mop-remarks-field2-caption',
  MOP_REMARKS_2_VALUE: 'mop-remarks-field2-value',
  DEBIT_BAL: 'debit-bal',
  CREDIT_BAL: 'credit-bal',
  CUM_BAL: 'cum-bal',
  TXN_DATE: 'txn-date',
  TXN_REC_NO: 'txn-rec-number',
  TXN_REC_AMOUNT: 'txn-rec-amount',
  REMARKS: 'txn-remarks',
  TXN_TYPE: 'txn-type',

  BOOKING_REFRENCE_NO: 'booking-reference-no',
  INV_DATE: 'invoice-date',
  HOTEL_NAME: 'hotel-name',
  HOTEL_ADDRESS: 'hotel-address',
  HOTEL_CITY_NAME: 'hotel-city-name',
  HOTEL_STATE_NAME: 'hotel-state-name',
  HOTEL_COUNTRY_NAME: 'hotel-country-name',
  HOTEL_POSTAL_CODE: 'hotel-postal-code',
  HOTEL_EMAIL_1: 'hotel-email-1',
  
  CHECK_IN_DATE: 'check-in-date',
  CHECK_OUT_DATE: 'chech-out-date',
  PAY_STATUS: 'pay-status',
  CLIENT_CURRENCY: 'client-currency',
  CLIENTSALEPRICE: 'clientsaleprice',
  CLIENT_SALE_PRICE: 'clientsaleprice',
  CLIENT_SALE_PRICE_TAX_VALUE: 'client-sale-price-tax-value',
  CLIENT_SALE_PRICE_NET: 'client-sale-price-net',
  CLIENT_SALE_PROFIT: 'client-sale-profit',


  SUPPLIER_NAME: 'supplier-name',
  SUPPLIER_ADDRESS: 'supplier-address',
  SUPPLIER_CITY_NAME: 'supplier-city-name',
  SUPPLIER_STATE_NAME: 'supplier-state-name',
  SUPPLIER_COUNTRY_NAME: 'supplier-country-name',
  SUPPLIER_POSTAL_CODE: 'supplier-postal-code',
  SUPPLIER_EMAIL_1: 'supplier-email-1',
  PRODUCT_NAME: 'product-name',
};

export { reportConstants };
